tasks:
  - name: Init
    init: pnpm install && docker-compose pull
    command: cp .env.example .env && && docker-compose up -d && pnpm run dev

ports:
  - port: 4000
    visibility: public
    onOpen: open-browser
  - port: 3000
    visibility: public
    onOpen: ignore
  - port: 3306
    visibility: public
    onOpen: ignore